In [5]:
from HPA_CC.data.dataset import RefCLSDM
from config import FUCCI_DS_PATH

In [15]:
full_datamodule = RefCLSDM(FUCCI_DS_PATH, "minimal", 32, 1, "phase", split=(0.64, 0.16, 0.20), concat_well_stats=True, scope=True)
print(len(full_datamodule.dataset))
X, Y_raw = full_datamodule.dataset.X, full_datamodule.dataset.Y
Y = Y_raw.argmax(axis=1)
print(X.shape, Y.shape)

Loading /data/ishang/FUCCI-dataset-well/embeddings_minimal_dino_hpa.pt
Loading /data/ishang/FUCCI-dataset-well/intensity_distributions_minimal.pt
X shape before intensity stats: torch.Size([31737, 1536])
X shape: torch.Size([31737, 2048])
Loading /data/ishang/FUCCI-dataset-well/minimal_sample_phase_scope.pt
Y shape: torch.Size([31737, 4])
31737
torch.Size([31737, 2048]) torch.Size([31737])


In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Create a KNN classifier
knn = KNeighborsClassifier(n_neighbors=10)

# Fit the classifier to the data
knn.fit(X_train, Y_train)

# Predict the labels for the test data
Y_pred = knn.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(Y_test, Y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

# Compute confusion matrix
cm = confusion_matrix(Y_test, Y_pred)

print(cm)



Accuracy: 57.75%
[[  57   52    4   27]
 [  16 1656  376  202]
 [   9  550  689  480]
 [  15  358  593 1264]]
